#Porta
server.port=9580

#Lista de órgãos a serem migrados
#Deve ser separado por virgula ex:
#Se ficar vazio a rotina migrará documentos de todos os órgãos
sempapel.orgaos=
sempapel.migrar.modelo=true
sempapel.migrar.preenchimento=true
sempapel.migrar.movimentacao=true
sempapel.migrar.documento=true

hcp.thread.maximo=1001

#Teste de carga no HCP
hcp.test.halitado=false
hcp.test.total.arquivo=2000
hcp.test.tamanho.minimo=1
hcp.test.tamanho.maximo=10
hcp.test.tamanho.incremento=9
hcp.test.thread.minimo=200
hcp.test.thread.incremento=200

sempapel.hcp.usuario=###PREENCHER###
sempapel.hcp.senha=###PREENCHER###
sempapel.hcp.uri=###PREENCHER###

# Datasource
spring.datasource.url=###PREENCHER###
spring.datasource.username=siga
spring.datasource.password=###PREENCHER###
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts = true

spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type=trace